version: v1.0
name: Initial Pipeline
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
blocks:
  - name: 'Block #1'
    task:
      secrets:
        - name: api-keys
      jobs:
      - name: Build
        commands:
          - checkout
          - docker build . -t ci
          - docker run -it -e GH_PERSONAL_TOKEN=${GH_PERSONAL_TOKEN} ci
